#!/usr/bin/env bash
# check-state-freshness.sh — Check all STATE files for freshness + live data consistency
# Usage: bash check-state-freshness.sh
#
# Checks:
# 1. All 7 STATE_[MODULE].md files for staleness (>7 days)
# 2. zjp-metrics.json (auto-generated SSOT) against live GitHub API data (P-2, pool, alerts)
# 3. GH_PAT expiry (only flags at ≤7 days per Rule 18)
# 4. TODO.md blocker freshness (flags blocked items, warns if TODO stale >7 days)
#
# Run at session start (part of VERIFY step).

set -euo pipefail

STATE_DIR="/mnt/c/Users/Mahd/Videos/Work/Business/.GenAI_Work/projects/zjp/state"
STALE_THRESHOLD=7

echo "=== State File Freshness Check (all modules) ==="
echo ""

# --- Phase 1: Freshness of all 7 STATE files ---

MODULES=(TAG ENR AGG SUP OUT DASH INF)
STALE_COUNT=0

for MOD in "${MODULES[@]}"; do
  FILE="$STATE_DIR/STATE_${MOD}.md"
  if [ ! -f "$FILE" ]; then
    echo "  ${MOD}: FILE NOT FOUND at $FILE"
    STALE_COUNT=$((STALE_COUNT + 1))
    continue
  fi

  STATE_DATE=$(grep -oP 'Last Updated:\*?\*?\s+\K\d{4}-\d{2}-\d{2}' "$FILE" 2>/dev/null | head -1 || echo "NOT_FOUND")

  if [ "$STATE_DATE" = "NOT_FOUND" ]; then
    echo "  ${MOD}: No date header found — check format"
    continue
  fi

  DAYS_AGO=$(( ( $(date +%s) - $(date -d "$STATE_DATE" +%s) ) / 86400 ))

  if [ "$DAYS_AGO" -gt "$STALE_THRESHOLD" ]; then
    echo "  ${MOD}: STALE — ${DAYS_AGO} days old (${STATE_DATE}). Threshold: ${STALE_THRESHOLD} days."
    STALE_COUNT=$((STALE_COUNT + 1))
  else
    echo "  ${MOD}: OK — ${DAYS_AGO} days old (${STATE_DATE})"
  fi
done

echo ""

# --- Phase 2: zjp-metrics.json live-data checks ---

echo "=== Live Data Consistency (zjp-metrics.json → live API) ==="
echo ""

# Try multiple known paths for zjp-metrics.json
# Path 1: jobs-data-2026 (canonical — generated by collect-metrics workflow)
# Path 2: jobs-aggregator-private (generated by generate-zjp-metrics in fetch-jobs)
METRICS=""
for REPO_PATH in \
  "repos/zapplyjobs/jobs-data-2026/contents/.github/data/zjp-metrics.json" \
  "repos/zapplyjobs/jobs-aggregator-private/contents/.github/data/zjp-metrics.json"; do
  RAW=$(gh api "$REPO_PATH" --jq '.content' 2>/dev/null | base64 -d 2>/dev/null || echo "")
  if [ -n "$RAW" ] && echo "$RAW" | python3 -c "import sys,json; json.load(sys.stdin)" 2>/dev/null; then
    METRICS="$RAW"
    break
  fi
done

if [ -z "$METRICS" ]; then
  echo "  WARN: Could not fetch zjp-metrics.json from any known path"
  echo "  WARN: Metrics generation may be broken (E42 observation: workflow files missing from repo tree)"
else
  # P-2 alignment from metrics vs live repo check
  METRICS_HASH=$(echo "$METRICS" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('submodules',{}).get('hash',''))" 2>/dev/null)
  METRICS_P2=$(echo "$METRICS" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('submodules',{}).get('p2_status',''))" 2>/dev/null)

  if [ -n "$METRICS_HASH" ]; then
    LIVE_SHA=$(gh api repos/zapplyjobs/jobs-aggregator-private/contents/.github/scripts/shared \
      --jq '.sha' 2>/dev/null || echo "FETCH_ERROR")
    if [ "$LIVE_SHA" != "FETCH_ERROR" ]; then
      PREFIX="${LIVE_SHA:0:${#METRICS_HASH}}"
      if [ "$PREFIX" = "$METRICS_HASH" ]; then
        echo "  P-2: METRICS=${METRICS_HASH:0:12} | LIVE=${LIVE_SHA:0:12} | OK"
      else
        echo "  P-2: STALE — METRICS=${METRICS_HASH:0:12} | LIVE=${LIVE_SHA:0:12} | Pipeline may need to catch up"
      fi
    fi
  else
    echo "  P-2: ${METRICS_P2:-unknown}"
  fi

  # Pool count from metrics
  METRICS_POOL=$(echo "$METRICS" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('pool',{}).get('total_jobs','?'))" 2>/dev/null)
  echo "  POOL: ${METRICS_POOL} jobs (from zjp-metrics.json)"

  # Enrichment from metrics
  METRICS_ENR_VER=$(echo "$METRICS" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('enrichment',{}).get('enricher_version','?'))" 2>/dev/null)
  METRICS_ENR_RATE=$(echo "$METRICS" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('enrichment',{}).get('enrichment_rate_pct','?'))" 2>/dev/null)
  echo "  ENR: v${METRICS_ENR_VER} | ${METRICS_ENR_RATE}% enriched"

  # Alert status
  METRICS_ALERT=$(echo "$METRICS" | python3 -c "import sys,json; d=json.load(sys.stdin); print('ACTIVE' if d.get('alerts',{}).get('active') else 'CLEAR')" 2>/dev/null)
  echo "  ALERTS: ${METRICS_ALERT}"

  # Metrics freshness
  METRICS_GEN=$(echo "$METRICS" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('generated_at','?'))" 2>/dev/null)
  if [ "$METRICS_GEN" != "?" ] && [ "$METRICS_GEN" != "" ]; then
    METRICS_AGO=$(( ( $(date +%s) - $(date -d "$METRICS_GEN" +%s 2>/dev/null || echo 0) ) / 60 ))
    if [ "$METRICS_AGO" -gt 60 ]; then
      echo "  METRICS AGE: ${METRICS_AGO} min old — STALE (expected <30 min)"
    else
      echo "  METRICS AGE: ${METRICS_AGO} min old | OK"
    fi
  fi
fi

  # --- Phase 2.5: Runtime health from zjp-metrics.json ---

  echo ""
  echo "=== Runtime Health ==="
  echo ""

  RUNTIME_EXEC=$(echo "$METRICS" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('pipeline',{}).get('aggregator_execution_minutes',''))" 2>/dev/null)
  RUNTIME_QUEUE=$(echo "$METRICS" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('pipeline',{}).get('aggregator_queue_minutes',''))" 2>/dev/null)
  RUNTIME_CANCEL=$(echo "$METRICS" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('pipeline',{}).get('aggregator_cancel_count',''))" 2>/dev/null)
  RUNTIME_WALL=$(echo "$METRICS" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('pipeline',{}).get('aggregator_runtime_minutes',''))" 2>/dev/null)

  if [ -n "$RUNTIME_EXEC" ] && [ "$RUNTIME_EXEC" != "None" ]; then
    if (( $(echo "$RUNTIME_EXEC > 15" | bc -l 2>/dev/null || echo 0) )); then
      echo "  EXECUTION: ${RUNTIME_EXEC} min — HIGH (threshold: 15 min)"
    else
      echo "  EXECUTION: ${RUNTIME_EXEC} min | OK"
    fi
  else
    echo "  EXECUTION: — (awaiting next metrics cycle)"
  fi

  if [ -n "$RUNTIME_QUEUE" ] && [ "$RUNTIME_QUEUE" != "None" ]; then
    if (( $(echo "$RUNTIME_QUEUE > 5" | bc -l 2>/dev/null || echo 0) )); then
      echo "  QUEUE: ${RUNTIME_QUEUE} min — HIGH (frequent overlap)"
    else
      echo "  QUEUE: ${RUNTIME_QUEUE} min | OK"
    fi
  else
    echo "  QUEUE: — (awaiting next metrics cycle)"
  fi

  if [ -n "$RUNTIME_CANCEL" ] && [ "$RUNTIME_CANCEL" != "None" ]; then
    if [ "$RUNTIME_CANCEL" -gt 3 ] 2>/dev/null; then
      echo "  CANCELLED: ${RUNTIME_CANCEL}/15 runs — HIGH (>20% overlap)"
    else
      echo "  CANCELLED: ${RUNTIME_CANCEL}/15 runs | OK"
    fi
  else
    echo "  CANCELLED: — (awaiting next metrics cycle)"
  fi

  if [ -n "$RUNTIME_WALL" ] && [ "$RUNTIME_WALL" != "None" ]; then
    echo "  WALL TIME: ${RUNTIME_WALL} min (total incl. queue)"
  fi

  # INF-OBSERV-3: Per-stage timing breakdown
  STAGE_TIMINGS=$(echo "$METRICS" | python3 -c "
import sys, json
d = json.load(sys.stdin)
st = d.get('pipeline', {}).get('stage_timings', {})
if not st or all(v == 0 for v in st.values()):
    print('  STAGES: no data — stage_timings not yet collected')
else:
    total = sum(st.values())
    for k in sorted(st.keys()):
        ms = st[k]
        pct = round(ms / max(total, 1) * 100)
        print(f'  STAGE {k}: {ms/1000:.1f}s ({pct}%)')
    print(f'  STAGE TOTAL: {total/1000:.1f}s')
" 2>/dev/null)
  echo "$STAGE_TIMINGS"

# GH_PAT expiry (Rule 18: only flag at ≤7 days)
PAT_EXPIRY="2026-05-30"
DAYS_LEFT=$(( ( $(date -d "$PAT_EXPIRY" +%s) - $(date +%s) ) / 86400 ))
if [ "$DAYS_LEFT" -le 7 ]; then
  echo "  PAT: CRITICAL — GH_PAT expires in ${DAYS_LEFT} days — rotate immediately"
fi

echo ""

# --- Phase 3: Workflow enablement check ---

echo "=== Workflow Enablement ==="
echo ""

# Check ALL workflows dynamically (not hardcoded) — catches disabled_manually AND disabled_inactivity
REPOS=(
  zapplyjobs/jobs-aggregator-private
  zapplyjobs/jobs-data-2026
  zapplyjobs/New-Grad-Jobs-2026
  zapplyjobs/Internships-2026
  zapplyjobs/New-Grad-Software-Engineering-Jobs-2026
  zapplyjobs/New-Grad-Data-Science-Jobs-2026
  zapplyjobs/New-Grad-Hardware-Engineering-Jobs-2026
  zapplyjobs/New-Grad-Healthcare-Jobs-2026
  zapplyjobs/job-board-shared
)

DISABLED_COUNT=0
TOTAL_WF=0

for REPO in "${REPOS[@]}"; do
  REPO_NAME="${REPO#zapplyjobs/}"
  WF_DATA=$(gh api "repos/$REPO/actions/workflows" --jq '.workflows[] | "\(.path | sub(".github/workflows/"; ""))|\(.state)"' 2>/dev/null || echo "")
  if [ -z "$WF_DATA" ]; then
    continue
  fi
  while IFS='|' read -r WF STATE; do
    TOTAL_WF=$((TOTAL_WF + 1))
    if [ "$STATE" = "disabled_manually" ] || [ "$STATE" = "disabled_inactivity" ]; then
      echo "  DISABLED ($STATE): ${REPO_NAME}/${WF}"
      DISABLED_COUNT=$((DISABLED_COUNT + 1))
    fi
  done <<< "$WF_DATA"
done

if [ "$DISABLED_COUNT" -eq 0 ]; then
  echo "  All ${TOTAL_WF} workflows enabled | OK"
fi

echo ""

# --- Phase 3.5: TODO Blocker Freshness ---

echo "=== TODO Blocker Freshness ==="
echo ""

TODO_FILE="/mnt/c/Users/Mahd/Videos/Work/Business/.GenAI_Work/projects/zjp/TODO.md"
TODO_UPDATED=$(grep -m1 "Last Updated" "$TODO_FILE" 2>/dev/null | grep -oP '\d{4}-\d{2}-\d{2}' || echo "")
BLOCKER_LINES=$(grep -in "blocked" "$TODO_FILE" 2>/dev/null | grep -v "No longer blocked" | grep -v "unblocked" || echo "")

if [ -z "$BLOCKER_LINES" ]; then
  echo "  No active blockers in TODO | OK"
else
  BLOCKER_COUNT=$(echo "$BLOCKER_LINES" | wc -l)
  echo "  Found ${BLOCKER_COUNT} blocked item(s):"
  echo "$BLOCKER_LINES" | while IFS= read -r line; do
    LINENUM=$(echo "$line" | cut -d: -f1)
    CONTENT=$(echo "$line" | cut -d: -f2- | head -c 120)
    echo "    L${LINENUM}: ${CONTENT}"
  done
  if [ -n "$TODO_UPDATED" ]; then
    TODO_AGO=$(( ( $(date +%s) - $(date -d "$TODO_UPDATED" +%s 2>/dev/null || echo 0) ) / 86400 ))
    if [ "$TODO_AGO" -gt "$STALE_THRESHOLD" ]; then
      echo "  TODO last updated ${TODO_AGO} days ago — blockers may be stale. Verify each blocker is still valid."
    else
      echo "  TODO updated ${TODO_AGO} day(s) ago | OK"
    fi
  fi
fi

echo ""

# --- Summary ---
if [ "$STALE_COUNT" -gt 0 ]; then
  echo "=== Result: ${STALE_COUNT} stale STATE file(s). Refresh before trusting claims. ==="
else
  echo "=== Result: All 7 STATE files fresh. zjp-metrics.json is SSOT for pipeline numbers. ==="
fi
